language: node_js
node_js: stable


install:
  - cd ./mark
  - npm install

script:  
  - node index.js
  - cd ..
  - git init
  - git config user.name "vczero"
  - git config user.email "wlhmyit@126.com" 
  - ls
  - git add .
  - git commit -am 'update docs; docs -> website'
  - git push --force --quiet "https://${gh-pages}@${GH_REF}" gh-pages:gh-pages  

#after_script:
  


branches:
  only:
    - doc
  env:
    global:
    - GH_REF: github.com/vczero/dockit.git 





