language: node_js
node_js: stable

env:
 global:
   - GH_REF: github.com/vczero/dockit.git 

install:
  - cd ./mark
  - npm install


script:
  - node index.js
  - cd ..
  - git config user.name "vczero"
  - git config user.email "wlhmyit@126.com"
  - git checkout -b gh-pages
  - git merge doc
  - git status
  - git add .
  - git status
  - git commit -am 'update website' -f -q https://vczero:${gh_token}@github.com/vczero/dockit-gh-pages gh-pages &2>/dev/null
  - git status
  - git push -f -q https://vczero:${gh_token}@github.com/vczero/dockit-gh-pages gh-pages &2>/dev/null


# after_script:
 

branches:
  only:
    - doc
