
language: ruby
rvm:
  - jruby
install:
  - sudo gem install travis
script:
  - travis login --github-token '${GH_TOKEN}'


language: node_js
node_js: stable


env:
 global:
   - GH_REF: github.com/vczero/dockit.git 

install:
  - cd ./mark
  - npm install
  
script:
  - node index.js
  - cd ..
  - git config user.name "vczero"
  - git config user.email "wlhmyit@126.com"
  - git checkout -b gh-pages
  - git merge doc
  - git status
  - git add .
  - git status
  - git commit -am 'update website'
  - git status
  - git push origin gh-pages


# after_script:
 
branches:
  only:
    - doc
